package parsing.tokenizer

enum class WordType(vararg val atoms: WordAtom): WordDescriptor {
	OPERATOR(
		WordAtom.NOT,
		WordAtom.AND,
		WordAtom.OR,
		WordAtom.INCREMENT,
		WordAtom.DECREMENT,
		WordAtom.PLUS,
		WordAtom.MINUS,
		WordAtom.STAR,
		WordAtom.SLASH,
		WordAtom.ADD,
		WordAtom.SUBTRACT,
		WordAtom.MULTIPLY,
		WordAtom.DIVIDE,
		WordAtom.EQUALS,
		WordAtom.NOT_EQUALS,
		WordAtom.GREATER_OR_EQUALS,
		WordAtom.LOWER_OR_EQUALS,
		WordAtom.GREATER,
		WordAtom.LOWER),
	UNARY_OPERATOR(
		WordAtom.NOT,
		WordAtom.PLUS,
		WordAtom.MINUS,
		WordAtom.TRIPLE_DOT),
	UNARY_MODIFICATION(
		WordAtom.INCREMENT,
		WordAtom.DECREMENT),
	BINARY_MODIFICATION(
		WordAtom.ADD,
		WordAtom.SUBTRACT,
		WordAtom.MULTIPLY,
		WordAtom.DIVIDE),
	BINARY_BOOLEAN_OPERATOR(
		WordAtom.AND,
		WordAtom.OR),
	UNION_OPERATOR(
		WordAtom.AND,
		WordAtom.OR),
	ADDITION(
		WordAtom.PLUS,
		WordAtom.MINUS),
	MULTIPLICATION(
		WordAtom.STAR,
		WordAtom.SLASH),
	EQUALITY(
		WordAtom.EQUALS,
		WordAtom.NOT_EQUALS),
	COMPARISON(
		WordAtom.GREATER_OR_EQUALS,
		WordAtom.LOWER_OR_EQUALS,
		WordAtom.GREATER,
		WordAtom.LOWER),
	CAST(
		WordAtom.AS,
		WordAtom.OPTIONAL_CAST,
		WordAtom.FORCE_CAST,
		WordAtom.IS,
		WordAtom.IS_NOT),
	FUNCTION_DECLARATION(
		WordAtom.TO,
		WordAtom.IT),
	VARIABLE_DECLARATION(
		WordAtom.CONST,
		WordAtom.VAR,
		WordAtom.VAL),
	MEMBER_ACCESSOR(
		WordAtom.DOT,
		WordAtom.OPTIONAL_ACCESSOR),
	GENERICS_START(
		WordAtom.LOWER),
	GENERICS_END(
		WordAtom.GREATER),
	GENERICS_MODIFIER(
		WordAtom.CONSUMING,
		WordAtom.PRODUCING),
	TYPE_TYPE(
		WordAtom.CLASS,
		WordAtom.OBJECT,
		WordAtom.TRAIT,
		WordAtom.ENUM),
	MODIFIER(
		WordAtom.NATIVE,
		WordAtom.OVERRIDE,
		WordAtom.IMM,
		WordAtom.MUT,
		WordAtom.TRIPLE_DOT),
	DEFINITION_MODIFIER(
		WordAtom.NATIVE,
		WordAtom.IMM,
		WordAtom.MUT),
	MEMBER_MODIFIER(
		WordAtom.NATIVE,
		WordAtom.OVERRIDE,
		WordAtom.IMM,
		WordAtom.MUT),
	PARAMETER_MODIFIER(
		WordAtom.IMM,
		WordAtom.MUT,
		WordAtom.TRIPLE_DOT),
	TRY(
		WordAtom.TRY_OPTIONAL,
		WordAtom.TRY_UNCHECK);

	override fun includes(atom: WordAtom?): Boolean {
		return atoms.contains(atom)
	}
}